version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.2.0
  aws-ecs: circleci/aws-ecs@02.2.1

jobs:
  build:
    docker:
      - image: circleci/node:18
    steps:
      - checkout
      - run: npm install
      - run:
          name: Build Docker image
          command: |
            docker build -t graphbook:$CIRCLE_SHA1 -f src/server/Dockerfile .
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    docker:
      - image: circleci/node:18
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm install
      - run:
          name: Install dependencies for tests
          command: npm install --only=dev
          environment:
            NODE_ENV: production

  deploy:
    docker:
      - image: circleci/python:3.8.5
    steps:
      - checkout
      - attach_workspace:
          at: .
      - aws-ecr/build-and-push-image:
          repo: "graphbook"
          tag: "${CIRCLE_SHA1}"
      - aws-ecs/deploy-service-update:
          family: "graphbook-task-definition"
          cluster-name: "graphbook-cluster"
          service-name: "graphbook-service"
          container-image-name-updates: "container=graphbook-container,tag=${CIRCLE_SHA1}"

workflows:
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test